version: 0.2

phases:
  build:
    commands:
      - chmod +x ./gradlew
      - ./gradlew assembleDebug
      - ./gradlew testDebugUnitTest
artifacts:
  files:
    - './android/app/build/outputs/**/*.apk'
  discard-paths: yes
