name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build
      run: ./gradlew assembleDebug
    - name: Test
      run: ./gradlew testDebugUnitTest

  dependency-review:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Dependency Review
      uses: actions/dependency-review-action@v3
      with:
        fail-on-severity: moderate
        allow-licenses: GPL-3.0, BSD-3-Clause, MIT
        deny-licenses: LGPL-2.0, BSD-2-Clause
        allow-ghsas: GHSA-abcd-1234-5679, GHSA-efgh-1234-5679
        fail-on-scopes: development, runtime

